# Default values for flask-app
replicaCount: 1

image:
  repository: flask-demo-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5001

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: flask-app.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nameOverride: ""
fullnameOverride: ""
